### ISSUE TITLE
Locks up when downloading (big?) files

### ISSUE THREAD

**Issue by kattjevfel** [QuadPiece/QuadFile#2]
Every time someone starts a download of a file it seems to stop accepting new connections. This becomes a real problem when dealing with bigger files (1GB+), in fact it renders the whole site useless as no one can connect and end up with 504 gateway timeouts instead.

I've tested connecting straight to localhost while loading a big file and it doesn't connect until I stop the download. I really really really wanna use this piece of software as it does nearly exactly what I want :(

Steps to reproduce:
1. Upload big file (~1GB)
2. Start download
3. Try load any other file
4. Watch it struggle but finally load after download has been stopped.

**Comment by QuadPiece** [comment]
This is simply how flask operates by default. I've considered a migration to [Sanic](https://github.com/channelcat/sanic) to fix this.

The current solution to this issue is firing up the application using gunicorn and setting the number of workers that gunicorn should use.

Installing gunicorn and starting the server using the WSGI gateway with `gunicorn wsgi:app -w 4 --bind 127.0.0.1:<preferred port> --log-file /some/location/quadfile.log` will start the application with 4 workers, meaning it can handle 4 concurrent connections. Increasing this worker limit is the simplest way to scale QuadFile. For more efficient scaling it's probably possible to get gunicorn's async workers to run (`eventlet `, `gevent` and `tornado`)

But as the application is currently built, using more gunicorn workers should not pose much of an issue since the application doesn't consume many much ram per worker. (in fact the file.quad.moe site runs on 8 workers and only consumes about 80-90 MB of ram, Ubuntu's usage included)

It's not recommended to run QuadFile without gunicorn outside of test environments or very, very small personal instances.
